apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=  # "postgres" in base64
  POSTGRES_PASSWORD: c2VjdXJlUGFzc3dvcmQ=  # "securePassword" in base64
  DATABASE_URL: cG9zdGdyZXM6Ly9wb3N0Z3JlczpzZWN1cmVQYXNzd29yZEBwb3N0Z3JlczoxNTQzMi9hY3Rpdml0eWRi  # base64 encoded connection URL
# Encode values using echo -n "value" | base64