services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB} 
    # ports:
    #   - "5432:5432"   
    volumes:
      - postgres_sm_data:/var/lib/postgresql/data
    networks:
      - app-network
      - monitoring
  postgres-exporter:
    image: wrouesnel/postgres_exporter
    container_name: postgres-exporter
    env_file:
      - .env
    # ports:
    #   - "9187:9187"
    depends_on:
      - postgres
    networks:
      - monitoring    
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin  
    networks:
      - app-network
  redis:
    image: redis:latest
    container_name: redis-container
    restart: unless-stopped
    networks:
      - app-network
      - monitoring
  redis_exporter:
    image: oliver006/redis_exporter:latest
    container_name: redis_exporter
    # ports:
    #   - "9121:9121"
    environment:
      REDIS_ADDR: "redis:6379"
    depends_on:
      - redis
    networks:
      - app-network
      - monitoring        
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - USERS_CONTAINER=users-${USERS_VERSION} # or directly in .env file  
      - POSTS_CONTAINER=posts-${USERS_VERSION} # or directly in .env file  
      - FOLLOWERS_CONTAINER=followers-${FOLLOWERS_VERSION} # or directly in .env file
      - COMMENTS_CONTAINER=comments-${COMMENTS_VERSION} # or directly in .env file
      - REACTIONS_CONTAINER=reactions-${COMMENTS_VERSION} # or directly in .env file
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - ./certs:/etc/caddy/certs
    networks:
      - app-network
      - monitoring      
  caddy-ui:
    image: qmcgaw/caddy-ui:latest
    ports:
      - "4000:8000"  # Change as needed
    environment:
      - CADDY_API_ENDPOINT=http://caddy:2019
    depends_on:
      - caddy
    networks:
      - app-network
      - monitoring      
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    # ports:
    #   - "9090:9090"
    depends_on:
      - redis_exporter  
    networks:
      - monitoring
  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    depends_on:
      - tempo
    networks:
      - app-network
      - monitoring

  # Grafana Tempo
  tempo:
    container_name: tempo
    image: grafana/tempo:latest
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
    networks:
      - monitoring    

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    depends_on:
      - prometheus  
    networks:
      - monitoring    
  users:
    build:
      context: ./users
      args:
        VERSION: ${USERS_VERSION}
    container_name: users${USERS_VERSION}
    restart: always
    depends_on:
      - postgres
      - redis
    env_file:
      - ./users/.env
    # Uncomment below to test in postman  
    ports:
      - "8080:8080"
    networks:
      - app-network
  followers:
    build:
      context: ./followers
      args:
        VERSION: ${FOLLOWERS_VERSION}
    container_name: followers${FOLLOWERS_VERSION}
    restart: always
    depends_on:
      - postgres
      - redis
      - users
    env_file:
      - ./followers/.env
    # Uncomment below to test in postman  
    # ports:
    #   - "8081:8080"
    networks:
      - app-network    
  posts:
    build:
      context: ./posts
      args:
        VERSION: ${POSTS_VERSION}
    container_name: posts${POSTS_VERSION}
    restart: always
    depends_on:
      - postgres
      - redis
      - users
    env_file:
      - ./posts/.env
    # Uncomment below to test in postman  
    ports:
      - "8085:8080"
    networks:
      - app-network
  comments:
    build:
      context: ./comments
      args:
        VERSION: ${COMMENTS_VERSION}
    container_name: comments${COMMENTS_VERSION}
    restart: always
    depends_on:
      - postgres
      - redis
      - users
      - posts
    env_file:
      - ./comments/.env
    # Uncomment below to test in postman  
    ports:
      - "8083:8080"
    networks:
      - app-network
  reactions:
    build:
      context: ./reactions
      args:
        VERSION: ${REACTIONS_VERSION}
    container_name: reactions${REACTIONS_VERSION}
    restart: always
    depends_on:
      - postgres
      - redis
      - posts
      - comments
    env_file:
      - ./reactions/.env
    # Uncomment below to test in postman  
    ports:
      - "8084:8080"
    networks:
      - app-network                    
  notifications:
    build:
      context: ./notifications
      args:
        VERSION: ${NOTIFICATIONS_VERSION}
    container_name: notifications${NOTIFICATIONS_VERSION}
    restart: always
    depends_on:
      - users
    env_file:
      - ./notifications/.env
    # Uncomment below to test in postman    
    # ports:
    #   - "8086:8080"
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - "8087:8080"
    environment:
      SWAGGER_JSON: /openapi.yaml
    volumes:
      - ./openapi.yaml:/openapi.yaml  
    networks:
      - app-network      
volumes:
  postgres_sm_data:
    driver: local
  pgadmin-data:
    driver: local
  caddy_data:
    driver: local
  caddy_config:  
    driver: local
  grafana_data:
    driver: local  
networks:
  app-network:
    driver: bridge
  monitoring:      
    driver: bridge