CREATE TABLE comments ( id SERIAL PRIMARY KEY,
    user_id INT NOT NULL,
    entity_id INT NOT NULL,
    content TEXT NOT NULL,
    status VARCHAR(20) DEFAULT 'active',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);