services:
  postgres:
    image: postgres:15
    container_name: postgres_activity
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_sm_data:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_activity
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin  
  # redis:
  #   image: redis:latest
  #   container_name: redis-container
  #   ports:
  #     - "6379:6379"
  #   restart: unless-stopped
volumes:
  postgres_sm_data:
    driver: local
  pgadmin-data:
    driver: local
