name: Build and Push Services

on:
  workflow_run:
    workflows: ["Build and Test"]  # Name of the first workflow
    types:
      - completed
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'  # Runs only if the first workflow succeeds
    strategy:
      matrix:
        service: [users, posts, notifications]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check if ${{ matrix.service }} has changed
        id: check_changes
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep "^${{ matrix.service }}/"; then
            echo "changed=true" >> $GITHUB_ENV
          else
            echo "changed=false" >> $GITHUB_ENV
          fi

      - name: Read version from VERSION file
        if: env.changed == 'true'
        id: version
        run: echo "VERSION=$(cat ${{ matrix.service }}/VERSION)" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        if: env.changed == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker Image
        if: env.changed == 'true'
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}
          VERSION_TAG=${{ env.VERSION }}
          docker build -t $IMAGE_NAME:$VERSION_TAG -t $IMAGE_NAME:latest ${{ matrix.service }}
          docker push $IMAGE_NAME:$VERSION_TAG
          docker push $IMAGE_NAME:latest
        continue-on-error: false